### ISSUE TITLE
Getting error with Quark

### ISSUE THREAD

**Issue by syrinka** [NullaDev/VanillaMagic#2]
此 mod 在 1.18.2 下与夸克的 **management > Item Sharing** 选项冲突，会导致填充核心后的魔杖与一些需要填充物的核心的名称缺失，类似于：`世界交互法杖(  )`

In 1.18.2 this mod conflicts with Quark's **management > Item Sharing** option.

**Comment by Kanbe-Kotori** [comment]
本项目已经重制到1.19.2并停止维护
see: https://github.com/NullaDev/Technical-Cores
